apiVersion: v1
kind: Service
metadata:
  name: node-app-service
  namespace: basic-deploy
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3000 
      nodePort: 30086 
  type: NodePort